run: MidMeeting
	java MidMeeting

City: City.java
	javac City.java

Connection: Connection.java
	javac Connection.java

MidMeeting: City Connection MidMeeting.java
	javac MidMeeting.java

clean:
	rm *.class 
